### ISSUE TITLE
不会删除，右下方没有百度的delete

### ISSUE THREAD

**Issue by herbsama** [message163/web#1]
满哥啥时候混到主管，让我这种也能混进去，我5年内就跳一次的打算

**Comment by message163** [comment]
有人五年了 还是小兵

**Comment by herbsama** [comment]
狗混五年也是五年老狗，请对自己自信点，满哥忙的雅痞还能更新视频已经很秀了，就是想问下看文档看不进去一定要tb买视频学习吗？满哥，看文档不实操就只有一点点印象
